export const hotelsInfo = [
	{
		id:1,
		title: "Light bright airy stylish apt & safe peaceful stay",
		features: ["Wif Air conditioning Kitchen", "Cancellation fexibility availiable"],
		ratings: 4.9,
		totalRating: 20,
		price: 34,
		guest: 4,
		rooms: 2,
		beds: 2,
		bathrooms: 2,
		cords: { lat: 21.4171963, lng: 91.977232 },
		imgUrl: "https://i.ibb.co/KXX7Wmn/travel-img-1.png",
	},
	{
		id:2,
		title: "Apartment in Lost Panorama",
			guest: 4,
			rooms: 2,
			beds: 2,
			bathrooms: 2,
		
		features: ["Wif Air conditioning Kitchen", "Cancellation fexibility availiable"],
		ratings: 4.5,
		totalRating: 15,
		price: 52,
		cords: { lat: 21.4172171, lng: 91.9772095 },
		imgUrl: "https://i.ibb.co/w7NjLP1/travel-img-2.png",
	},
	{
		id:3,
		title: "AR Lounge & Pool (r&r + b&b)",
		guest: 4,
		rooms: 2,
		beds: 2,
		bathrooms: 2,
		features: ["Wif Air conditioning Kitchen", "Cancellation fexibility availiable"],
		ratings: 4.9,
		totalRating: 25,
		price: 44,
		cords: { lat: 21.4172171, lng: 91.9772095 },
		imgUrl: "https://i.ibb.co/wYMBf0w/travel-img-3.png",
	},
];
